### PR TITLE
Add Grunt tasks

### PR DESCRIPTION
**Pull request by dannytranlx**
@juliangarritano @alavers @mspensieri @jpjoyal 

Will also follow with supportkit/supportkit-ios#66

### CODE REVIEW

**Comment by juliangarritano** [comment]
Nice!
:+1:

**Comment by alavers** [comment]
:+1:

**Comment by mspensieri** [comment]
Don't think this repo really needs an integration branch... aren't `master` and `gh-pages` enough?

**Comment by dannytranlx** [comment]
There's actually no `master` right now :confused:

**Pull request merged**
